/***
 * Copyright (2023) Hewlett Packard Enterprise Development LP
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * You may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ***/

/**
 * -----------------------------------------------------------------------------
 * Hierarchical Lineage Flow
 * -----------------------------------------------------------------------------
 *
 * This component renders an interactive hierarchical lineage graph using
 * React Flow and Dagre. It transforms lineage data into a structured
 * top-down visualization consisting of Pipeline, Stage, and Execution
 * nodes connected by directional edges.
 *
 * This file acts as the main orchestration layer for building, laying out,
 * and rendering the complete lineage visualization.
 * -----------------------------------------------------------------------------
 */

import React, { useMemo } from "react";
import dagre from "dagre";
import "./index.css";
import { TransformLineageData } from "../TransformLineageData";
import { buildReactFlowEdges, buildReactFlowNodes, nodeWidth, LineageCanvas } from "../LineageFlowCommon";
import LineageNode from "../LineageNode";
 ; // adjust the path to wherever you place the shared file

const nodeHeight = 80;

const StageGroupNode = ({ data, style }) => (
  <div
    className="stage-group-card"
    style={{
      ...style,
      width: data.width || style?.width,
      height: data.height || style?.height,
    }}
  />
);

const nodeTypes = { lineageNode: LineageNode, stageGroup: StageGroupNode };

// Central color of Pipeline, Stage, StageGroup, and Execution nodes in the lineage tree
const getNodeThemeColor = (type) => {
  switch (type) {
    case "Pipeline": return "#10b981"; // Green
    case "Stage": return "#f59e0b";   // Amber / Orange
    case "StageGroup": return "#ffffff"; // White for minimap stage cards
    case "Model": return "#f59e0b";   // Alias fallback
    case "Node": return "#ffffff"; // White for minimap cards
    case "Execution": return "#3b82f6"; // Blue
    default: return "#ffffff";        // White
  }
};

// Layout reconfigured for a top-down vertical tree structure with side-by-side spacing
// The core layout engine, using dagre for "Backbone" and manual math for Execution leaves.
const getLayoutedElements = (nodes = [], edges = []) => {
  const g = new dagre.graphlib.Graph();

  g.setGraph({
    rankdir: "TB",
    ranksep: 110,       // Vertical gap between Pipeline and Stages
    nodesep: 100,       // Even horizontal spacing between stage groups
    edgesep: 20,
    marginx: 40,
    marginy: 40
  });

  // STEP 1: Only feed non-Execution nodes (Pipeline & Stages) into Dagre
  nodes.forEach((node) => {
    if (node.data?.type !== "Execution") {
      g.setNode(node.id, { width: nodeWidth, height: nodeHeight });
    }
  });

  // Only feed edges that don't point to an execution node into Dagre
  edges.forEach((edge) => {
    const targetNode = nodes.find((n) => n.id === edge.target);
    if (targetNode && targetNode.data?.type !== "Execution") {
      g.setEdge(edge.source, edge.target, { weight: 10, minlen: 1 });
    }
  });

  // Layout the main horizontal backbone (Pipeline -> Stages)
  dagre.layout(g);

  // STEP 2: Group the execution leaves manually by their stage parent
  const parentToExecutionLeavesMap = {};
  nodes.forEach((node) => {
    if (node.data?.type === "Execution") {
      const parentEdge = edges.find((e) => e.target === node.id);
      if (parentEdge) {
        const pId = parentEdge.source;
        if (!parentToExecutionLeavesMap[pId]) parentToExecutionLeavesMap[pId] = [];
        parentToExecutionLeavesMap[pId].push(node.id);
      }
    }
  });

  // STEP 3: Assign positions to all elements
  return nodes?.map((node) => {
    // Default top-down connection routing
    node.targetPosition = 'top';
    node.sourcePosition = 'bottom';

    if (node.data?.type !== "Execution") {
      // Use the compact positions generated by Dagre for main stages
      const pos = g.node(node.id) || { x: 0, y: 0 };
      node.position = {
        x: pos.x - nodeWidth / 2,
        y: pos.y - nodeHeight / 2,
      };
    } else {
      // Calculate clean, compact vertical positions for Execution nodes
      const parentEdge = edges.find((e) => e.target === node.id);
      if (parentEdge) {
        const parentId = parentEdge.source;
        const parentPos = g.node(parentId) || { x: 0, y: 0 };
        const siblings = parentToExecutionLeavesMap[parentId] || [];
        const siblingIndex = siblings.indexOf(node.id);

        node.position = {
          x: parentPos.x - nodeWidth / 2,
          // Increased gap: was +20, now +40 for clearer separation between stacked nodes
          y: (parentPos.y + nodeHeight / 2) + 60 + (siblingIndex * (nodeHeight + 40)),
        };
      }
    }
    return node;
  });
};

// Write below getStageGroupNodes function for added the block for each particular stage.
const getStageGroupNodes = (layoutedNodes, edges) => {
  const stageNodes = layoutedNodes.filter((node) => node.data?.type === "Stage");

  return stageNodes.map((stageNode) => {
    const groupChildren = [stageNode];
    const childEdges = edges.filter((edge) => edge.source === stageNode.id);

    childEdges.forEach((edge) => {
      const childNode = layoutedNodes.find((node) => node.id === edge.target);
      if (childNode) {
        groupChildren.push(childNode);
      }
    });

    const xMin = Math.min(...groupChildren.map((child) => child.position.x));
    const yMin = Math.min(...groupChildren.map((child) => child.position.y));
    const xMax = Math.max(...groupChildren.map((child) => child.position.x + (child.width || nodeWidth)));
    const yMax = Math.max(...groupChildren.map((child) => child.position.y + (child.height || nodeHeight)));
    const paddingX = 32;
    const paddingY = 40;

    const groupWidth = xMax - xMin + paddingX * 2;
    const groupHeight = yMax - yMin + paddingY * 2;

    return {
      id: `stage-group-${stageNode.id}`,
      type: "stageGroup",
      position: { x: xMin - paddingX, y: yMin - paddingY },
      data: {
        label: stageNode.data?.name || "Stage",
        type: "StageGroup",
        width: groupWidth,
        height: groupHeight,
      },
      selectable: false,
      draggable: false,
      style: {
        pointerEvents: "none",
      },
      zIndex: 0,
    };
  });
};

const HierarchicalLineageFlow = ({ data }) => {
  const { nodes, edges } = useMemo(() => {
    if (!data || data.length === 0) return { nodes: [], edges: [] };

    const formattedData = TransformLineageData(data);
    const rfNodes = buildReactFlowNodes(formattedData?.nodes);
    const rfEdges = buildReactFlowEdges(formattedData?.links ?? formattedData?.edges ?? [], {
      edgeType: "step",
      markerColor: "#4b5563",
      stroke: "#374151",
      strokeWidth: 3,
    });

    // Layout uses the FULL edge list so every execution sibling gets
    // correctly positioned in its vertical stack
    const layoutedNodes = getLayoutedElements(rfNodes, rfEdges);
    const stageGroupNodes = getStageGroupNodes(layoutedNodes, rfEdges);

    // Keep only the first Stage -> Execution edge per stage, hide subsequent execution links.
    const seenExecutionEdgeForSource = new Set();
    const renderEdges = rfEdges.filter((edge) => {
      const targetNode = layoutedNodes.find((n) => n.id === edge.target);
      if (targetNode?.data?.type === "Execution") {
        if (seenExecutionEdgeForSource.has(edge.source)) {
          return false;
        }
        seenExecutionEdgeForSource.add(edge.source);
        return true;
      }
      return true;
    });

    return {
      nodes: [...stageGroupNodes, ...layoutedNodes],
      edges: renderEdges,
    };
  }, [data]);

  return (
    <LineageCanvas
      nodes={nodes}
      edges={edges}
      nodeTypes={nodeTypes}
      colorFn={getNodeThemeColor}
      fitViewOptions={{ padding: 0.15, includeHiddenNodes: true }}
      defaultViewport={{ x: 0, y: 0, zoom: 1 }}
      maxZoom={2}
    />
  );
};

export default HierarchicalLineageFlow;