apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data
spec:
  capacity:
    storage: {{ .Values.cmf_service.pvc.data.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/cmf/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-env
spec:
  capacity:
    storage: {{ .Values.cmf_service.pvc.env.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/cmf/data/env
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-static
spec:
  capacity:
    storage: {{ .Values.cmf_service.pvc.static.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/cmf/data/static
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-server-data-labels
spec:
  capacity:
    storage: {{ .Values.cmf_service.pvc.labels.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/cmf/data/labels
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-tensorboard-logs
spec:
  capacity:
    storage: {{ .Values.tensorboard_service.pvc.logs.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/cmf/data/tensorboard-logs
