apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cmf_service.pvc.data.storage }}
  volumeName: pv-server-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-env
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cmf_service.pvc.env.storage }}
  volumeName: pv-server-data-env
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cmf_service.pvc.static.storage }}
  volumeName: pv-server-data-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-server-data-labels
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cmf_service.pvc.labels.storage }}
  volumeName: pv-server-data-labels
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tensorboard-logs
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.tensorboard_service.pvc.logs.storage }}
  volumeName: pv-tensorboard-logs
