apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard-deployment
  labels:
    app: tensorboard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tensorboard
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        image: "{{ .Values.tensorboard_service.image.repository }}:{{ .Values.tensorboard_service.image.tag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        command: ["/bin/bash", "-c"]
        args:
          - tensorboard --logdir /logs --host 0.0.0.0 --path_prefix=/tensorboard
        ports:
        - containerPort: {{ .Values.tensorboard_service.service.port }}
        volumeMounts:
        - name: tensorboard-logs
          mountPath: /logs
        readinessProbe:
          httpGet:
            path: /tensorboard
            port: {{ .Values.tensorboard_service.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /tensorboard
            port: {{ .Values.tensorboard_service.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: tensorboard-logs
        persistentVolumeClaim:
          claimName: pvc-tensorboard-logs
---
apiVersion: v1
kind: Service
metadata:
  name: tensorboard
  labels:
    app: tensorboard
spec:
  type: {{ .Values.tensorboard_service.service.type }}
  selector:
    app: tensorboard
  ports:
  - name: http
    port: {{ .Values.tensorboard_service.service.port }}
    targetPort: {{ .Values.tensorboard_service.service.port }}
