###
# Copyright (2026) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###

# Use PostgreSQL 17 on Debian Bookworm as the base image.
FROM docker.io/library/postgres:17-bookworm

# Run subsequent build commands as root.
USER root

# Update package metadata.
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl gnupg \
    && install -d /usr/share/postgresql-common/pgdg \
    && curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc \
    && . /etc/os-release \
    && echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt ${VERSION_CODENAME}-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends postgresql-13 \
    && rm -rf /var/lib/apt/lists/*

# Copy the PostgreSQL upgrade script into the image.
COPY upgrade-postgres.sh /usr/local/bin/upgrade-postgres.sh
# Make the upgrade script executable.
RUN chmod +x /usr/local/bin/upgrade-postgres.sh

# Run the upgrade script when the container starts.
ENTRYPOINT ["/usr/local/bin/upgrade-postgres.sh"]