apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/data  

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-logs
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/logs 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-import
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/import 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-plugins
spec:
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/plugins  

