vars:
    - configs/MIAOD-GRAY.py:data_root
    - al_cycle.json:al_cycle,next_cycle,al_seed
    - uuid.json:uuid_var

stages:
    input_sample_lists:
        cmd:
            python input_lists.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --labeled ${data_root}/training.txt --unlabeled ${data_root}/unlabeled.txt --seed ${al_seed} --train ${data_root}/train.txt --selected work_dirs/test/X_L_${al_cycle}.npy --unselected work_dirs/test/X_U_${al_cycle}.npy --stage_name input_sample_lists --execution_name ${uuid_var}
        deps:
            - ${data_root}/training.txt
            - ${data_root}/unlabeled.txt
        outs:
            - ${data_root}/train.txt
            - work_dirs/test/X_L_${al_cycle}.npy
            - work_dirs/test/X_U_${al_cycle}.npy
        params:
            - configs/MIAOD-GRAY.py:
                - data_root
            - al_cycle.json:
                - al_cycle
                - al_seed

    active_learning_training:
        cmd:
            #single gpu
            python cycle_train.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --cycle ${al_cycle} --labeled work_dirs/test/X_L_${al_cycle}.npy --unselected work_dirs/test/X_U_${al_cycle}.npy --seed ${al_seed} --model work_dirs/test/cycle.pth --stage_name active_learning_training --execution_name ${uuid_var}
            #distributed mode
            #python -m torch.distributed.launch --nproc_per_node=2 --master_port=39025  cycle_train.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --cycle ${al_cycle} --labeled work_dirs/test/X_L_${al_cycle}.npy --unselected work_dirs/test/X_U_${al_cycle}.npy --seed ${al_seed} --model work_dirs/test/cycle.pth --gpus 2 --launcher pytorch --stage_name active_learning_training --execution_name ${uuid_var}
        deps:
            - work_dirs/test/X_L_${al_cycle}.npy
            - work_dirs/test/X_U_${al_cycle}.npy
            - uuid.json
        outs:
            - work_dirs/test/cycle.pth
        params:
            - configs/MIAOD-GRAY.py:
                - data_root
            - al_cycle.json:
                - al_cycle
                - al_seed

    active_learning_selection:
        cmd:
            #single gpu
            python cycle_select.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --cycle ${al_cycle} --model work_dirs/test/cycle.pth --labeled work_dirs/test/X_L_${al_cycle}.npy --seed ${al_seed} --labeled_next work_dirs/test/X_L_${next_cycle}.npy --unselected work_dirs/test/X_U_${next_cycle}.npy --bbox_output work_dirs/test/labeling_hints_${next_cycle}.txt --stage_name active_learning_selection --execution_name ${uuid_var}
            #distributed mode
            #python -m torch.distributed.launch --nproc_per_node=2 --master_port=39016  cycle_select.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --cycle ${al_cycle} --model work_dirs/test/cycle.pth --labeled work_dirs/test/X_L_${al_cycle}.npy --seed ${al_seed} --labeled_next work_dirs/test/X_L_${next_cycle}.npy --unselected work_dirs/test/X_U_${next_cycle}.npy --bbox_output work_dirs/test/labeling_hints_${next_cycle}.txt --gpus 2 --launcher pytorch --stage_name active_learning_selection --execution_name ${uuid_var}
        deps:
            - work_dirs/test/cycle.pth
            - work_dirs/test/X_L_${al_cycle}.npy
            - uuid.json
        outs:
            - work_dirs/test/X_L_${next_cycle}.npy
            - work_dirs/test/X_U_${next_cycle}.npy
        params:
            - configs/MIAOD-GRAY.py:
                - data_root
            - al_cycle.json:
                - al_cycle
                - next_cycle
                - al_seed

    
    output_sample_lists:
        cmd:
            python output_lists.py configs/MIAOD-GRAY.py --work_directory work_dirs/test --selected work_dirs/test/X_L_${al_cycle}.npy --selected_next work_dirs/test/X_L_${next_cycle}.npy --train ${data_root}/train.txt --map ${data_root}/map.txt --seed ${al_seed} --label_next ${data_root}/label_next.txt --labeled ${data_root}/training_next.txt --unlabeled ${data_root}/unlabeled_next.txt --cycle_config al_cycle.json --cycle_config_next al_cycle_next.json --stage_name output_sample_lists --execution_name ${uuid_var}
        deps:
            - work_dirs/test/X_L_${al_cycle}.npy
            - work_dirs/test/X_L_${next_cycle}.npy
            - ${data_root}/train.txt 
            - ${data_root}/map.txt
        outs:
            - ${data_root}/label_next.txt
            - ${data_root}/training_next.txt
            - ${data_root}/unlabeled_next.txt
            - al_cycle_next.json
        params:
            - configs/MIAOD-GRAY.py:
                - data_root
            - al_cycle.json:
                - al_cycle
                - next_cycle
                - al_seed
