apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        - containerPort: {{ .Values.service.boltPort }}  
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: logs-volume
          mountPath: /logs
        - name: import-volume
          mountPath: /var/lib/neo4j/import
        - name: plugins-volume
          mountPath: /plugins
        env:
        - name: NEO4J_AUTH
          value: {{ .Values.neo4jAuth }}
        - name: NEO4J_dbms_connector_http_listen__address
          value: "0.0.0.0:{{ .Values.service.port }}"  
        - name: NEO4J_dbms_connector_bolt_listen__address
          value: "0.0.0.0:{{ .Values.service.boltPort }}" 
        - name: NEO4J_server_config_strict__validation_enabled
          value: "false"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: pvc-neo4j-data
      - name: logs-volume
        persistentVolumeClaim:
          claimName: pvc-neo4j-logs
      - name: import-volume
        persistentVolumeClaim:
          claimName: pvc-neo4j-import
      - name: plugins-volume
        persistentVolumeClaim:
          claimName: pvc-neo4j-plugins
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.port }}    
    targetPort: {{ .Values.service.port }}
    name: http
  - port: {{ .Values.service.boltPort }}  
    targetPort: {{ .Values.service.boltPort }}
    name: bolt
  selector:
    app: neo4j

