apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-data
spec:
  capacity:
    storage: {{ .Values.neo4j_service.pvc.data.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/data  

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-logs
spec:
  capacity:
    storage: {{ .Values.neo4j_service.pvc.logs.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/logs 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-import
spec:
  capacity:
    storage: {{ .Values.neo4j_service.pvc.import.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/import 

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-neo4j-plugins
spec:
  capacity:
    storage: {{ .Values.neo4j_service.pvc.plugins.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/neo4j/plugins  

