apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.data.storage }}  # Should match the size of the corresponding PV

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.logs.storage }}  # Should match the size of the corresponding PV

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-import
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.import.storage }}  # Should match the size of the corresponding PV

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-neo4j-plugins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.plugins.storage }}  # Should match the size of the corresponding PV