apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-cli
  template:
    metadata:
      labels:
        app: aws-cli
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for MinIO to be ready..."
          until curl -s http://minio:9000/minio/health/live; do
            sleep 3
          done
          echo "MinIO is ready. Creating bucket dvc-art..."
          aws --endpoint-url http://minio:9000 s3 mb s3://dvc-art --region eu-west-1 || exit 0
      restartPolicy: Always

