apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-data
spec:
  capacity:
    storage: {{ .Values.postgres_service.pvc.data.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/cmf/data/postgres_data
    type: DirectoryOrCreate
