version: '3.8'

services:

  aws:
    image: amazon/aws-cli
    container_name: aws-cli
    command: -c "sleep 2 && aws --endpoint-url http://${MYIP}:9000 s3 mb s3://dvc-art --region eu-west-1 || exit 0"
    entrypoint: [/bin/bash]
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - minio
