apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-data
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-postgres-data
